//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumWebMVC.Resources.Views.Topic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForumWebMVC.Resources.Views.Topic.Index.ru", typeof(Index_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр тем.
        /// </summary>
        internal static string Browse_Forums {
            get {
                return ResourceManager.GetString("Browse Forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщество форума.
        /// </summary>
        internal static string Lambda_Forums_community {
            get {
                return ResourceManager.GetString("Lambda Forums community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, прочитайте Правила форума перед созданием нового поста.
        /// </summary>
        internal static string Please_read_the_Forum_Guidelines_before_creating_a_new_post {
            get {
                return ResourceManager.GetString("Please read the Forum Guidelines before creating a new post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посты разделены на категории по языкам программирования или интересам.
        /// </summary>
        internal static string Posts_are_broadly_categorized_into_separate_forums_by_programming_language_or_area_of_interest {
            get {
                return ResourceManager.GetString("Posts are broadly categorized into separate forums by programming language or are" +
                        "a of interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to зарегистриравнным пользователем.
        /// </summary>
        internal static string registered_member {
            get {
                return ResourceManager.GetString("registered member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to чтобы создать новый пост.
        /// </summary>
        internal static string to_create_a_new_post {
            get {
                return ResourceManager.GetString("to create a new post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в .
        /// </summary>
        internal static string Welcome_to {
            get {
                return ResourceManager.GetString("Welcome to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы должны быть.
        /// </summary>
        internal static string You_must_be_a {
            get {
                return ResourceManager.GetString("You must be a", resourceCulture);
            }
        }
    }
}
