//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumWebMVC.Resources.Views.Topic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Topic_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Topic_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForumWebMVC.Resources.Views.Topic.Topic.de", typeof(Topic_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beitrag erstellen.
        /// </summary>
        internal static string Create_Post {
            get {
                return ResourceManager.GetString("Create Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        internal static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forum. Bitte halten Sie die Beiträge freundlich und themenbezogen.
        /// </summary>
        internal static string forum__Please_keep_posts_friendly_and_on_topic {
            get {
                return ResourceManager.GetString("forum. Please keep posts friendly and on-topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Keine Suchergebnisse gefunden für.
        /// </summary>
        internal static string No_search_results_found_for {
            get {
                return ResourceManager.GetString("No search results found for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Bitte lesen Sie die Forenrichtlinien, bevor Sie einen neuen Beitrag erstellen.
        /// </summary>
        internal static string Please_read_the_Forum_Guidelines_before_creating_a_new_post {
            get {
                return ResourceManager.GetString("Please read the Forum Guidelines before creating a new post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Frage Antwort.
        /// </summary>
        internal static string question_answer {
            get {
                return ResourceManager.GetString("question_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registriertes Mitglied.
        /// </summary>
        internal static string registered_member {
            get {
                return ResourceManager.GetString("registered member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Antworten.
        /// </summary>
        internal static string Replies {
            get {
                return ResourceManager.GetString("Replies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche....
        /// </summary>
        internal static string Search___ {
            get {
                return ResourceManager.GetString("Search...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to um einen neuen Beitrag zu erstellen.
        /// </summary>
        internal static string to_create_a_new_post {
            get {
                return ResourceManager.GetString("to create a new post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Willkommen zu.
        /// </summary>
        internal static string Welcome_to_the {
            get {
                return ResourceManager.GetString("Welcome to the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Sie müssen ein.
        /// </summary>
        internal static string You_must_be_a {
            get {
                return ResourceManager.GetString("You must be a", resourceCulture);
            }
        }
    }
}
